export const sources = [
  {
    id: "elpais-espana",
    country: "Espana",
    name: "El Pais",
    type: "Generalista",
    siteUrl: "https://elpais.com/espana/",
    feedUrl: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/portada",
    defaultTopic: "Gobernabilidad",
    allowUrlPatterns: ["/espana/", "/opinion/"],
    maxItems: 12,
  },
  {
    id: "elmundo-espana",
    country: "Espana",
    name: "El Mundo",
    type: "Generalista",
    siteUrl: "https://www.elmundo.es/espana.html",
    feedUrl: "https://e00-elmundo.uecdn.es/elmundo/rss/espana.xml",
    defaultTopic: "Gobernabilidad",
    allowUrlPatterns: ["/espana/", "/andalucia/", "/madrid/", "/pais-vasco/", "/baleares/"],
    maxItems: 12,
  },
  {
    id: "animal-politico-mexico",
    country: "Mexico",
    name: "Animal Politico",
    type: "Investigacion",
    siteUrl: "https://animalpolitico.com/",
    feedUrl: "https://animalpolitico.com/feed/",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "proceso-mexico",
    country: "Mexico",
    name: "Proceso",
    type: "Investigacion",
    siteUrl: "https://www.proceso.com.mx/",
    feedUrl: "https://www.proceso.com.mx/rss",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "plaza-publica-guatemala",
    country: "Guatemala",
    name: "Plaza Publica",
    type: "Investigacion",
    siteUrl: "https://www.plazapublica.com.gt/",
    feedUrl: "https://www.plazapublica.com.gt/rss.xml",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "elfaro-salvador",
    country: "El Salvador",
    name: "El Faro",
    type: "Investigacion",
    siteUrl: "https://elfaro.net/",
    feedUrl: "https://elfaro.net/feed",
    defaultTopic: "Seguridad",
    enabled: false,
  },
  {
    id: "confidencial-nicaragua",
    country: "Nicaragua",
    name: "Confidencial",
    type: "Investigacion",
    siteUrl: "https://confidencial.digital/",
    feedUrl: "https://confidencial.digital/feed/",
    defaultTopic: "Instituciones",
    blockUrlPatterns: ["/pxmolina/", "/deportes/", "/farandula/"],
    maxItems: 16,
  },
  {
    id: "14ymedio-cuba",
    country: "Cuba",
    name: "14ymedio",
    type: "Digital",
    siteUrl: "https://www.14ymedio.com/",
    feedUrl: "https://www.14ymedio.com/rss",
    defaultTopic: "Sociedad",
    allowUrlPatterns: ["/cuba/", "/internacional/"],
    maxItems: 16,
  },
  {
    id: "lasilla-colombia",
    country: "Colombia",
    name: "La Silla Vacia",
    type: "Analisis",
    siteUrl: "https://www.lasillavacia.com/",
    feedUrl: "https://www.lasillavacia.com/feed/",
    defaultTopic: "Gobernabilidad",
    blockUrlPatterns: ["/deportes/", "/podcast/"],
    maxItems: 16,
  },
  {
    id: "elespectador-colombia",
    country: "Colombia",
    name: "El Espectador",
    type: "Generalista",
    siteUrl: "https://www.elespectador.com/politica/",
    feedUrl: "https://www.elespectador.com/rss/politica/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "efecto-cocuyo-venezuela",
    country: "Venezuela",
    name: "Efecto Cocuyo",
    type: "Digital",
    siteUrl: "https://efectococuyo.com/",
    feedUrl: "https://efectococuyo.com/feed/",
    defaultTopic: "Diplomacia",
    allowUrlPatterns: ["/politica/", "/internacionales/", "/la-humanidad/", "/economia/"],
    maxItems: 16,
  },
  {
    id: "primicias-ecuador",
    country: "Ecuador",
    name: "Primicias",
    type: "Digital",
    siteUrl: "https://www.primicias.ec/politica/",
    feedUrl: "https://www.primicias.ec/feed/",
    defaultTopic: "Seguridad",
    allowUrlPatterns: ["/politica/", "/economia/", "/seguridad/"],
    maxItems: 16,
  },
  {
    id: "ojo-publico-peru",
    country: "Peru",
    name: "Ojo Publico",
    type: "Investigacion",
    siteUrl: "https://ojo-publico.com/",
    feedUrl: "https://ojo-publico.com/feed",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "elcomercio-peru",
    country: "Peru",
    name: "El Comercio",
    type: "Generalista",
    siteUrl: "https://elcomercio.pe/politica/",
    feedUrl: "https://elcomercio.pe/arcio/rss/",
    defaultTopic: "Gobernabilidad",
    allowUrlPatterns: ["/politica/", "/economia/", "/mundo/"],
    blockUrlPatterns: ["/deporte-total/", "/mag/", "/tvmas/", "/luces/", "/provecho/", "/viajes/", "/somos/"],
    maxItems: 24,
  },
  {
    id: "ciper-chile",
    country: "Chile",
    name: "CIPER",
    type: "Investigacion",
    siteUrl: "https://www.ciperchile.cl/",
    feedUrl: "https://www.ciperchile.cl/feed/",
    defaultTopic: "Probidad",
    maxItems: 14,
  },
  {
    id: "latercera-chile",
    country: "Chile",
    name: "La Tercera",
    type: "Generalista",
    siteUrl: "https://www.latercera.com/politica/",
    feedUrl: "https://www.latercera.com/feed/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "lanacion-argentina",
    country: "Argentina",
    name: "La Nacion",
    type: "Generalista",
    siteUrl: "https://www.lanacion.com.ar/politica/",
    feedUrl: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/category/politica/?outputType=xml",
    defaultTopic: "Economia politica",
    allowUrlPatterns: ["/politica/", "/economia/"],
    maxItems: 14,
  },
  {
    id: "infobae-argentina",
    country: "Argentina",
    name: "Infobae",
    type: "Digital",
    siteUrl: "https://www.infobae.com/politica/",
    feedUrl: "https://www.infobae.com/feeds/rss/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "ladiaria-uruguay",
    country: "Uruguay",
    name: "La Diaria",
    type: "Analisis",
    siteUrl: "https://ladiaria.com.uy/politica/",
    feedUrl: "https://ladiaria.com.uy/feeds/articulos/",
    defaultTopic: "Elecciones",
    allowUrlPatterns: ["/politica/", "/opinion/"],
    blockUrlPatterns: ["/humor/", "/deporte/", "/cotidiana/"],
    maxItems: 18,
  },
];
