export const sources = [
  {
    id: "elpais-espana",
    country: "España",
    name: "El País",
    type: "Generalista",
    siteUrl: "https://elpais.com/espana/",
    feedUrl: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/portada",
    defaultTopic: "Gobernabilidad",
  },
  {
    id: "elmundo-espana",
    country: "España",
    name: "El Mundo",
    type: "Generalista",
    siteUrl: "https://www.elmundo.es/espana.html",
    feedUrl: "https://e00-elmundo.uecdn.es/elmundo/rss/espana.xml",
    defaultTopic: "Gobernabilidad",
  },
  {
    id: "animal-politico-mexico",
    country: "México",
    name: "Animal Político",
    type: "Investigación",
    siteUrl: "https://animalpolitico.com/",
    feedUrl: "https://animalpolitico.com/feed/",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "proceso-mexico",
    country: "México",
    name: "Proceso",
    type: "Investigación",
    siteUrl: "https://www.proceso.com.mx/",
    feedUrl: "https://www.proceso.com.mx/rss",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "plaza-publica-guatemala",
    country: "Guatemala",
    name: "Plaza Pública",
    type: "Investigación",
    siteUrl: "https://www.plazapublica.com.gt/",
    feedUrl: "https://www.plazapublica.com.gt/rss.xml",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "elfaro-salvador",
    country: "El Salvador",
    name: "El Faro",
    type: "Investigación",
    siteUrl: "https://elfaro.net/",
    feedUrl: "https://elfaro.net/feed",
    defaultTopic: "Seguridad",
    enabled: false,
  },
  {
    id: "confidencial-nicaragua",
    country: "Nicaragua",
    name: "Confidencial",
    type: "Investigación",
    siteUrl: "https://confidencial.digital/",
    feedUrl: "https://confidencial.digital/feed/",
    defaultTopic: "Instituciones",
  },
  {
    id: "14ymedio-cuba",
    country: "Cuba",
    name: "14ymedio",
    type: "Digital",
    siteUrl: "https://www.14ymedio.com/",
    feedUrl: "https://www.14ymedio.com/rss",
    defaultTopic: "Sociedad",
  },
  {
    id: "lasilla-colombia",
    country: "Colombia",
    name: "La Silla Vacía",
    type: "Análisis",
    siteUrl: "https://www.lasillavacia.com/",
    feedUrl: "https://www.lasillavacia.com/feed/",
    defaultTopic: "Gobernabilidad",
  },
  {
    id: "elespectador-colombia",
    country: "Colombia",
    name: "El Espectador",
    type: "Generalista",
    siteUrl: "https://www.elespectador.com/politica/",
    feedUrl: "https://www.elespectador.com/rss/politica/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "efecto-cocuyo-venezuela",
    country: "Venezuela",
    name: "Efecto Cocuyo",
    type: "Digital",
    siteUrl: "https://efectococuyo.com/",
    feedUrl: "https://efectococuyo.com/feed/",
    defaultTopic: "Diplomacia",
  },
  {
    id: "primicias-ecuador",
    country: "Ecuador",
    name: "Primicias",
    type: "Digital",
    siteUrl: "https://www.primicias.ec/politica/",
    feedUrl: "https://www.primicias.ec/feed/",
    defaultTopic: "Seguridad",
  },
  {
    id: "ojo-publico-peru",
    country: "Perú",
    name: "Ojo Público",
    type: "Investigación",
    siteUrl: "https://ojo-publico.com/",
    feedUrl: "https://ojo-publico.com/feed",
    defaultTopic: "Instituciones",
    enabled: false,
  },
  {
    id: "elcomercio-peru",
    country: "Perú",
    name: "El Comercio",
    type: "Generalista",
    siteUrl: "https://elcomercio.pe/politica/",
    feedUrl: "https://elcomercio.pe/arcio/rss/",
    defaultTopic: "Gobernabilidad",
  },
  {
    id: "ciper-chile",
    country: "Chile",
    name: "CIPER",
    type: "Investigación",
    siteUrl: "https://www.ciperchile.cl/",
    feedUrl: "https://www.ciperchile.cl/feed/",
    defaultTopic: "Probidad",
  },
  {
    id: "latercera-chile",
    country: "Chile",
    name: "La Tercera",
    type: "Generalista",
    siteUrl: "https://www.latercera.com/politica/",
    feedUrl: "https://www.latercera.com/feed/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "lanacion-argentina",
    country: "Argentina",
    name: "La Nación",
    type: "Generalista",
    siteUrl: "https://www.lanacion.com.ar/politica/",
    feedUrl: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/category/politica/?outputType=xml",
    defaultTopic: "Economía política",
  },
  {
    id: "infobae-argentina",
    country: "Argentina",
    name: "Infobae",
    type: "Digital",
    siteUrl: "https://www.infobae.com/politica/",
    feedUrl: "https://www.infobae.com/feeds/rss/",
    defaultTopic: "Gobernabilidad",
    enabled: false,
  },
  {
    id: "ladiaria-uruguay",
    country: "Uruguay",
    name: "La Diaria",
    type: "Análisis",
    siteUrl: "https://ladiaria.com.uy/politica/",
    feedUrl: "https://ladiaria.com.uy/feeds/articulos/",
    defaultTopic: "Elecciones",
  },
];
