export const sourcesByCountry = [
  {
    country: "España",
    region: "Europa",
    sources: [
      ["El País", "Generalista", "https://elpais.com/espana/"],
      ["El Mundo", "Generalista", "https://www.elmundo.es/espana.html"],
      ["El Confidencial", "Política", "https://www.elconfidencial.com/espana/"],
      ["elDiario.es", "Política", "https://www.eldiario.es/politica/"],
      ["ABC", "Generalista", "https://www.abc.es/espana/"],
    ],
  },
  {
    country: "México",
    region: "Norteamérica",
    sources: [
      ["El Universal", "Generalista", "https://www.eluniversal.com.mx/nacion/"],
      ["Reforma", "Generalista", "https://www.reforma.com/"],
      ["Milenio", "Política", "https://www.milenio.com/politica"],
      ["Animal Político", "Investigación", "https://animalpolitico.com/"],
      ["Proceso", "Investigación", "https://www.proceso.com.mx/"],
    ],
  },
  {
    country: "Guatemala",
    region: "Centroamérica",
    sources: [
      ["Prensa Libre", "Generalista", "https://www.prensalibre.com/"],
      ["La Hora", "Política", "https://lahora.gt/"],
      ["Plaza Pública", "Investigación", "https://www.plazapublica.com.gt/"],
      ["Soy502", "Digital", "https://www.soy502.com/"],
    ],
  },
  {
    country: "Honduras",
    region: "Centroamérica",
    sources: [
      ["El Heraldo", "Generalista", "https://www.elheraldo.hn/"],
      ["La Prensa", "Generalista", "https://www.laprensa.hn/"],
      ["Criterio.hn", "Análisis", "https://criterio.hn/"],
    ],
  },
  {
    country: "El Salvador",
    region: "Centroamérica",
    sources: [
      ["La Prensa Gráfica", "Generalista", "https://www.laprensagrafica.com/"],
      ["El Faro", "Investigación", "https://elfaro.net/"],
      ["Diario El Mundo", "Generalista", "https://diario.elmundo.sv/"],
    ],
  },
  {
    country: "Nicaragua",
    region: "Centroamérica",
    sources: [
      ["Confidencial", "Investigación", "https://confidencial.digital/"],
      ["La Prensa", "Generalista", "https://www.laprensani.com/"],
      ["100% Noticias", "Digital", "https://100noticias.com.ni/"],
    ],
  },
  {
    country: "Costa Rica",
    region: "Centroamérica",
    sources: [
      ["La Nación", "Generalista", "https://www.nacion.com/"],
      ["CRHoy", "Digital", "https://www.crhoy.com/"],
      ["Semanario Universidad", "Análisis", "https://semanariouniversidad.com/"],
    ],
  },
  {
    country: "Panamá",
    region: "Centroamérica",
    sources: [
      ["La Prensa", "Generalista", "https://www.prensa.com/"],
      ["TVN Noticias", "TV/Digital", "https://www.tvn-2.com/"],
      ["Panamá América", "Generalista", "https://www.panamaamerica.com.pa/"],
    ],
  },
  {
    country: "Cuba",
    region: "Caribe",
    sources: [
      ["14ymedio", "Digital", "https://www.14ymedio.com/"],
      ["Diario de Cuba", "Digital", "https://diariodecuba.com/"],
      ["Cubanet", "Digital", "https://www.cubanet.org/"],
      ["Granma", "Oficial", "https://www.granma.cu/"],
    ],
  },
  {
    country: "República Dominicana",
    region: "Caribe",
    sources: [
      ["Listín Diario", "Generalista", "https://listindiario.com/"],
      ["Diario Libre", "Generalista", "https://www.diariolibre.com/"],
      ["Acento", "Análisis", "https://acento.com.do/"],
    ],
  },
  {
    country: "Puerto Rico",
    region: "Caribe",
    sources: [
      ["El Nuevo Día", "Generalista", "https://www.elnuevodia.com/"],
      ["Primera Hora", "Generalista", "https://www.primerahora.com/"],
      ["NotiCel", "Digital", "https://www.noticel.com/"],
    ],
  },
  {
    country: "Colombia",
    region: "Andes",
    sources: [
      ["El Tiempo", "Generalista", "https://www.eltiempo.com/politica"],
      ["El Espectador", "Generalista", "https://www.elespectador.com/politica/"],
      ["La Silla Vacía", "Análisis", "https://www.lasillavacia.com/"],
      ["Semana", "Generalista", "https://www.semana.com/politica/"],
    ],
  },
  {
    country: "Venezuela",
    region: "Andes/Caribe",
    sources: [
      ["El Nacional", "Generalista", "https://www.elnacional.com/"],
      ["Efecto Cocuyo", "Digital", "https://efectococuyo.com/"],
      ["TalCual", "Análisis", "https://talcualdigital.com/"],
      ["Runrun.es", "Investigación", "https://runrun.es/"],
    ],
  },
  {
    country: "Ecuador",
    region: "Andes",
    sources: [
      ["El Universo", "Generalista", "https://www.eluniverso.com/noticias/politica/"],
      ["Primicias", "Digital", "https://www.primicias.ec/politica/"],
      ["Expreso", "Generalista", "https://www.expreso.ec/actualidad/"],
      ["La Hora", "Generalista", "https://www.lahora.com.ec/"],
    ],
  },
  {
    country: "Perú",
    region: "Andes",
    sources: [
      ["El Comercio", "Generalista", "https://elcomercio.pe/politica/"],
      ["La República", "Generalista", "https://larepublica.pe/politica"],
      ["RPP", "Radio/Digital", "https://rpp.pe/politica"],
      ["Ojo Público", "Investigación", "https://ojo-publico.com/"],
    ],
  },
  {
    country: "Bolivia",
    region: "Andes",
    sources: [
      ["El Deber", "Generalista", "https://eldeber.com.bo/"],
      ["Los Tiempos", "Generalista", "https://www.lostiempos.com/"],
      ["La Razón", "Generalista", "https://www.la-razon.com/"],
      ["Brújula Digital", "Digital", "https://brujuladigital.net/"],
    ],
  },
  {
    country: "Paraguay",
    region: "Cono Sur",
    sources: [
      ["ABC Color", "Generalista", "https://www.abc.com.py/"],
      ["Última Hora", "Generalista", "https://www.ultimahora.com/"],
      ["La Nación", "Generalista", "https://www.lanacion.com.py/"],
    ],
  },
  {
    country: "Chile",
    region: "Cono Sur",
    sources: [
      ["La Tercera", "Generalista", "https://www.latercera.com/politica/"],
      ["Emol", "Generalista", "https://www.emol.com/noticias/Nacional/"],
      ["BioBioChile", "Digital", "https://www.biobiochile.cl/noticias/nacional.shtml"],
      ["CIPER", "Investigación", "https://www.ciperchile.cl/"],
    ],
  },
  {
    country: "Argentina",
    region: "Cono Sur",
    sources: [
      ["La Nación", "Generalista", "https://www.lanacion.com.ar/politica/"],
      ["Clarín", "Generalista", "https://www.clarin.com/politica/"],
      ["Página/12", "Generalista", "https://www.pagina12.com.ar/secciones/el-pais"],
      ["Perfil", "Política", "https://www.perfil.com/seccion/politica"],
      ["Infobae", "Digital", "https://www.infobae.com/politica/"],
    ],
  },
  {
    country: "Uruguay",
    region: "Cono Sur",
    sources: [
      ["El País Uruguay", "Generalista", "https://www.elpais.com.uy/"],
      ["El Observador", "Generalista", "https://www.elobservador.com.uy/"],
      ["La Diaria", "Análisis", "https://ladiaria.com.uy/politica/"],
    ],
  },
];

export const signals = [
  {
    country: "España",
    source: "El País",
    topic: "Gobernabilidad",
    priority: "Alta",
    title: "Tensión parlamentaria y pactos autonómicos reordenan la agenda nacional",
    summary:
      "Seguir impacto en presupuestos, investidura territorial, alianzas y coste reputacional de los bloques.",
    url: "https://elpais.com/espana/",
  },
  {
    country: "México",
    source: "Animal Político",
    topic: "Instituciones",
    priority: "Alta",
    title: "Reformas institucionales concentran la atención de partidos, cortes y sociedad civil",
    summary: "Vigilar cambios regulatorios, relación ejecutivo-judicial y respuesta de gobernadores.",
    url: "https://animalpolitico.com/",
  },
  {
    country: "Argentina",
    source: "La Nación",
    topic: "Economía política",
    priority: "Alta",
    title: "El ajuste fiscal tensiona coaliciones y gobernadores antes de nuevas negociaciones",
    summary: "Medir gobernabilidad legislativa, conflictividad social y condiciones de acuerdo con provincias.",
    url: "https://www.lanacion.com.ar/politica/",
  },
  {
    country: "Colombia",
    source: "La Silla Vacía",
    topic: "Seguridad",
    priority: "Alta",
    title: "Seguridad territorial y agenda de paz elevan el riesgo político regional",
    summary: "Cruzar hechos de orden público con negociaciones, opinión pública y elecciones locales.",
    url: "https://www.lasillavacia.com/",
  },
  {
    country: "Chile",
    source: "CIPER",
    topic: "Probidad",
    priority: "Media",
    title: "Investigaciones y financiamiento político mantienen presión sobre élites partidarias",
    summary: "Observar derivadas judiciales, respuesta parlamentaria y efectos en confianza institucional.",
    url: "https://www.ciperchile.cl/",
  },
  {
    country: "Perú",
    source: "Ojo Público",
    topic: "Gobernabilidad",
    priority: "Alta",
    title: "Fragmentación política complica reformas y aumenta volatilidad del Ejecutivo",
    summary: "Priorizar Congreso, fiscalía, protestas regionales y narrativa de estabilidad democrática.",
    url: "https://ojo-publico.com/",
  },
  {
    country: "Venezuela",
    source: "Efecto Cocuyo",
    topic: "Diplomacia",
    priority: "Alta",
    title: "Negociación externa, sanciones y oposición marcan el termómetro de riesgo",
    summary: "Seguir señales de Washington, Bruselas, Caracas y actores regionales de mediación.",
    url: "https://efectococuyo.com/",
  },
  {
    country: "El Salvador",
    source: "El Faro",
    topic: "Seguridad",
    priority: "Media",
    title: "El modelo de seguridad sigue condicionando debate constitucional y derechos",
    summary: "Separar datos de criminalidad, narrativa oficial, controles judiciales y crítica internacional.",
    url: "https://elfaro.net/",
  },
  {
    country: "Ecuador",
    source: "Primicias",
    topic: "Seguridad",
    priority: "Alta",
    title: "Crisis de seguridad redefine prioridades electorales y agenda económica",
    summary: "Revisar decretos, fuerzas de seguridad, crimen organizado y gobernabilidad provincial.",
    url: "https://www.primicias.ec/politica/",
  },
  {
    country: "Cuba",
    source: "14ymedio",
    topic: "Sociedad",
    priority: "Media",
    title: "Migración, economía doméstica y control político sostienen presión social",
    summary: "Contrastar fuentes oficiales, prensa independiente, remesas, energía y reacción ciudadana.",
    url: "https://www.14ymedio.com/",
  },
  {
    country: "Guatemala",
    source: "Plaza Pública",
    topic: "Instituciones",
    priority: "Media",
    title: "Justicia, fiscalía y Congreso son ejes de seguimiento para estabilidad democrática",
    summary: "Atender nombramientos, bloqueos legislativos, redes territoriales y movilización civil.",
    url: "https://www.plazapublica.com.gt/",
  },
  {
    country: "Uruguay",
    source: "La Diaria",
    topic: "Elecciones",
    priority: "Media",
    title: "Competencia partidaria y agenda social abren una fase de contraste programático",
    summary: "Comparar propuestas, encuestas, alianzas y continuidad de políticas públicas.",
    url: "https://ladiaria.com.uy/politica/",
  },
];
