export const sourcesByCountry = [
  {
    country: "Espana",
    region: "Europa",
    sources: [
      ["El Pais", "Generalista", "https://elpais.com/espana/"],
      ["El Mundo", "Generalista", "https://www.elmundo.es/espana.html"],
      ["El Confidencial", "Politica", "https://www.elconfidencial.com/espana/"],
      ["elDiario.es", "Politica", "https://www.eldiario.es/politica/"],
      ["ABC", "Generalista", "https://www.abc.es/espana/"],
    ],
  },
  {
    country: "Mexico",
    region: "Norteamerica",
    sources: [
      ["El Universal", "Generalista", "https://www.eluniversal.com.mx/nacion/"],
      ["Reforma", "Generalista", "https://www.reforma.com/"],
      ["Milenio", "Politica", "https://www.milenio.com/politica"],
      ["Animal Politico", "Investigacion", "https://animalpolitico.com/"],
      ["Proceso", "Investigacion", "https://www.proceso.com.mx/"],
    ],
  },
  {
    country: "Guatemala",
    region: "Centroamerica",
    sources: [
      ["Prensa Libre", "Generalista", "https://www.prensalibre.com/"],
      ["La Hora", "Politica", "https://lahora.gt/"],
      ["Plaza Publica", "Investigacion", "https://www.plazapublica.com.gt/"],
      ["Soy502", "Digital", "https://www.soy502.com/"],
    ],
  },
  {
    country: "Honduras",
    region: "Centroamerica",
    sources: [
      ["El Heraldo", "Generalista", "https://www.elheraldo.hn/"],
      ["La Prensa", "Generalista", "https://www.laprensa.hn/"],
      ["Criterio.hn", "Analisis", "https://criterio.hn/"],
    ],
  },
  {
    country: "El Salvador",
    region: "Centroamerica",
    sources: [
      ["La Prensa Grafica", "Generalista", "https://www.laprensagrafica.com/"],
      ["El Faro", "Investigacion", "https://elfaro.net/"],
      ["Diario El Mundo", "Generalista", "https://diario.elmundo.sv/"],
    ],
  },
  {
    country: "Nicaragua",
    region: "Centroamerica",
    sources: [
      ["Confidencial", "Investigacion", "https://confidencial.digital/"],
      ["La Prensa", "Generalista", "https://www.laprensani.com/"],
      ["100% Noticias", "Digital", "https://100noticias.com.ni/"],
    ],
  },
  {
    country: "Costa Rica",
    region: "Centroamerica",
    sources: [
      ["La Nacion", "Generalista", "https://www.nacion.com/"],
      ["CRHoy", "Digital", "https://www.crhoy.com/"],
      ["Semanario Universidad", "Analisis", "https://semanariouniversidad.com/"],
    ],
  },
  {
    country: "Panama",
    region: "Centroamerica",
    sources: [
      ["La Prensa", "Generalista", "https://www.prensa.com/"],
      ["TVN Noticias", "TV/Digital", "https://www.tvn-2.com/"],
      ["Panama America", "Generalista", "https://www.panamaamerica.com.pa/"],
    ],
  },
  {
    country: "Cuba",
    region: "Caribe",
    sources: [
      ["14ymedio", "Digital", "https://www.14ymedio.com/"],
      ["Diario de Cuba", "Digital", "https://diariodecuba.com/"],
      ["Cubanet", "Digital", "https://www.cubanet.org/"],
      ["Granma", "Oficial", "https://www.granma.cu/"],
    ],
  },
  {
    country: "Republica Dominicana",
    region: "Caribe",
    sources: [
      ["Listin Diario", "Generalista", "https://listindiario.com/"],
      ["Diario Libre", "Generalista", "https://www.diariolibre.com/"],
      ["Acento", "Analisis", "https://acento.com.do/"],
    ],
  },
  {
    country: "Puerto Rico",
    region: "Caribe",
    sources: [
      ["El Nuevo Dia", "Generalista", "https://www.elnuevodia.com/"],
      ["Primera Hora", "Generalista", "https://www.primerahora.com/"],
      ["NotiCel", "Digital", "https://www.noticel.com/"],
    ],
  },
  {
    country: "Colombia",
    region: "Andes",
    sources: [
      ["El Tiempo", "Generalista", "https://www.eltiempo.com/politica"],
      ["El Espectador", "Generalista", "https://www.elespectador.com/politica/"],
      ["La Silla Vacia", "Analisis", "https://www.lasillavacia.com/"],
      ["Semana", "Generalista", "https://www.semana.com/politica/"],
    ],
  },
  {
    country: "Venezuela",
    region: "Andes/Caribe",
    sources: [
      ["El Nacional", "Generalista", "https://www.elnacional.com/"],
      ["Efecto Cocuyo", "Digital", "https://efectococuyo.com/"],
      ["TalCual", "Analisis", "https://talcualdigital.com/"],
      ["Runrun.es", "Investigacion", "https://runrun.es/"],
    ],
  },
  {
    country: "Ecuador",
    region: "Andes",
    sources: [
      ["El Universo", "Generalista", "https://www.eluniverso.com/noticias/politica/"],
      ["Primicias", "Digital", "https://www.primicias.ec/politica/"],
      ["Expreso", "Generalista", "https://www.expreso.ec/actualidad/"],
      ["La Hora", "Generalista", "https://www.lahora.com.ec/"],
    ],
  },
  {
    country: "Peru",
    region: "Andes",
    sources: [
      ["El Comercio", "Generalista", "https://elcomercio.pe/politica/"],
      ["La Republica", "Generalista", "https://larepublica.pe/politica"],
      ["RPP", "Radio/Digital", "https://rpp.pe/politica"],
      ["Ojo Publico", "Investigacion", "https://ojo-publico.com/"],
    ],
  },
  {
    country: "Bolivia",
    region: "Andes",
    sources: [
      ["El Deber", "Generalista", "https://eldeber.com.bo/"],
      ["Los Tiempos", "Generalista", "https://www.lostiempos.com/"],
      ["La Razon", "Generalista", "https://www.la-razon.com/"],
      ["Brujula Digital", "Digital", "https://brujuladigital.net/"],
    ],
  },
  {
    country: "Paraguay",
    region: "Cono Sur",
    sources: [
      ["ABC Color", "Generalista", "https://www.abc.com.py/"],
      ["Ultima Hora", "Generalista", "https://www.ultimahora.com/"],
      ["La Nacion", "Generalista", "https://www.lanacion.com.py/"],
    ],
  },
  {
    country: "Chile",
    region: "Cono Sur",
    sources: [
      ["La Tercera", "Generalista", "https://www.latercera.com/politica/"],
      ["Emol", "Generalista", "https://www.emol.com/noticias/Nacional/"],
      ["BioBioChile", "Digital", "https://www.biobiochile.cl/noticias/nacional.shtml"],
      ["CIPER", "Investigacion", "https://www.ciperchile.cl/"],
    ],
  },
  {
    country: "Argentina",
    region: "Cono Sur",
    sources: [
      ["La Nacion", "Generalista", "https://www.lanacion.com.ar/politica/"],
      ["Clarin", "Generalista", "https://www.clarin.com/politica/"],
      ["Pagina/12", "Generalista", "https://www.pagina12.com.ar/secciones/el-pais"],
      ["Perfil", "Politica", "https://www.perfil.com/seccion/politica"],
      ["Infobae", "Digital", "https://www.infobae.com/politica/"],
    ],
  },
  {
    country: "Uruguay",
    region: "Cono Sur",
    sources: [
      ["El Pais Uruguay", "Generalista", "https://www.elpais.com.uy/"],
      ["El Observador", "Generalista", "https://www.elobservador.com.uy/"],
      ["La Diaria", "Analisis", "https://ladiaria.com.uy/politica/"],
    ],
  },
];

export const signals = [
  {
    country: "Espana",
    source: "El Pais",
    topic: "Gobernabilidad",
    priority: "Alta",
    title: "Tension parlamentaria y pactos autonomicos reordenan la agenda nacional",
    summary: "Seguir impacto en presupuestos, investidura territorial, alianzas y coste reputacional de los bloques.",
    url: "https://elpais.com/espana/",
  },
  {
    country: "Mexico",
    source: "Animal Politico",
    topic: "Instituciones",
    priority: "Alta",
    title: "Reformas institucionales concentran la atencion de partidos, cortes y sociedad civil",
    summary: "Vigilar cambios regulatorios, relacion ejecutivo-judicial y respuesta de gobernadores.",
    url: "https://animalpolitico.com/",
  },
  {
    country: "Argentina",
    source: "La Nacion",
    topic: "Economia politica",
    priority: "Alta",
    title: "El ajuste fiscal tensiona coaliciones y gobernadores antes de nuevas negociaciones",
    summary: "Medir gobernabilidad legislativa, conflictividad social y condiciones de acuerdo con provincias.",
    url: "https://www.lanacion.com.ar/politica/",
  },
  {
    country: "Colombia",
    source: "La Silla Vacia",
    topic: "Seguridad",
    priority: "Alta",
    title: "Seguridad territorial y agenda de paz elevan el riesgo politico regional",
    summary: "Cruzar hechos de orden publico con negociaciones, opinion publica y elecciones locales.",
    url: "https://www.lasillavacia.com/",
  },
  {
    country: "Chile",
    source: "CIPER",
    topic: "Probidad",
    priority: "Media",
    title: "Investigaciones y financiamiento politico mantienen presion sobre elites partidarias",
    summary: "Observar derivadas judiciales, respuesta parlamentaria y efectos en confianza institucional.",
    url: "https://www.ciperchile.cl/",
  },
  {
    country: "Peru",
    source: "Ojo Publico",
    topic: "Gobernabilidad",
    priority: "Alta",
    title: "Fragmentacion politica complica reformas y aumenta volatilidad del Ejecutivo",
    summary: "Priorizar Congreso, fiscalia, protestas regionales y narrativa de estabilidad democratica.",
    url: "https://ojo-publico.com/",
  },
  {
    country: "Venezuela",
    source: "Efecto Cocuyo",
    topic: "Diplomacia",
    priority: "Alta",
    title: "Negociacion externa, sanciones y oposicion marcan el termometro de riesgo",
    summary: "Seguir senales de Washington, Bruselas, Caracas y actores regionales de mediacion.",
    url: "https://efectococuyo.com/",
  },
  {
    country: "El Salvador",
    source: "El Faro",
    topic: "Seguridad",
    priority: "Media",
    title: "El modelo de seguridad sigue condicionando debate constitucional y derechos",
    summary: "Separar datos de criminalidad, narrativa oficial, controles judiciales y critica internacional.",
    url: "https://elfaro.net/",
  },
  {
    country: "Ecuador",
    source: "Primicias",
    topic: "Seguridad",
    priority: "Alta",
    title: "Crisis de seguridad redefine prioridades electorales y agenda economica",
    summary: "Revisar decretos, fuerzas de seguridad, crimen organizado y gobernabilidad provincial.",
    url: "https://www.primicias.ec/politica/",
  },
  {
    country: "Cuba",
    source: "14ymedio",
    topic: "Sociedad",
    priority: "Media",
    title: "Migracion, economia domestica y control politico sostienen presion social",
    summary: "Contrastar fuentes oficiales, prensa independiente, remesas, energia y reaccion ciudadana.",
    url: "https://www.14ymedio.com/",
  },
  {
    country: "Guatemala",
    source: "Plaza Publica",
    topic: "Instituciones",
    priority: "Media",
    title: "Justicia, fiscalia y Congreso son ejes de seguimiento para estabilidad democratica",
    summary: "Atender nombramientos, bloqueos legislativos, redes territoriales y movilizacion civil.",
    url: "https://www.plazapublica.com.gt/",
  },
  {
    country: "Uruguay",
    source: "La Diaria",
    topic: "Elecciones",
    priority: "Media",
    title: "Competencia partidaria y agenda social abren una fase de contraste programatico",
    summary: "Comparar propuestas, encuestas, alianzas y continuidad de politicas publicas.",
    url: "https://ladiaria.com.uy/politica/",
  },
];
